name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devwithpug/ci-cd-with-github-actions:$(date +%s)
    - name: upload to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: devwithpug/ci-cd-with-github-actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
